<?php

/**
 * Implementation of hook_element_info_alter
 * Remove N/A option from radio button field
 * @param array $types
 */
function remove_na_element_info_alter(array &$types) {
    if (isset($types['radios'])) {
        $types['radios']['#process'][] = '_remove_na_remove_radio_na';
    }
}

/**
 * remove_radio_na
 * A Callback function for remove_na_element_info_alter
 * @param array $element
 * @return modified $element
 */
function _remove_na_remove_radio_na($element) {
    if (!empty($element['#field_name']) && $element['#field_name'] == 'field_contact_budget') {
        unset($element['_none']);
    }

    return $element;
}
